interface Env {
  SUPABASE_SERVICE_ROLE_KEY: string;
  R2_ACCESS_KEY_ID: string;
  R2_SECRET_ACCESS_KEY: string;
  TRANSCRIPTION_JOBS: Queue;
  SPEECHMATICS_API_KEY: string;
  TRANSCRIPTION_CALLBACK_TOKEN: string;
  PUBLIC_WORKER_URL: string;
}
